### ISSUE TITLE
Import tangled_up_in_unicode takes 120 seconds in Pycharm

### ISSUE THREAD

**Issue by bm765** [dylan-profiler/tangled-up-in-unicode#5]
Hi,

thanks for bringing this package to life! :-)

While using pandas_profiling, I realized that during debugging, the import of `tangled_up_in_unicode` takes 120 seconds when using Pycharm. During the normal (non debugging) execution, it takes only 0.3 seconds.

Is there anything that could be done for speeding up the debugging?

The code:
```python
import time
my_time = time.time()
import tangled_up_in_unicode

print(time.time() - my_time)
```

Result during debugging with Pycharm:

`125.81976366043091
`

**Comment by akx** [comment]
This is still an issue – trying to _work_ on the tangled package in PyCharm hangs the editor for long times, presumably because it's trying to do inference on the huge .py modules.
